// The 39 JEV rule questions, ported verbatim from the public JEV scan demo
// (vettd-beta /demo/jev-scan): instruction and criteria text are jev-1.13's wire input and must not
// be paraphrased. Everything else on each row (severity, routing) is Vettd's own decision; see
// vettd docs/spikes/jev-scan-emitter.md for the reasoning.
//
// `section` groups rules for the stage-2 evidence list. The demo only showed the sections of the
// rules that fired; the rest are inferred from the demo's contiguous question ordering.

import type {AssetFinding} from "../contract/scanner.js";

export type JevSeverity = AssetFinding["severity"];

export type JevRoute =
	| {type: "finding"}
	/** Emitted as a finding-shaped signal under an already-registered rule, beside Vettd's own row. */
	| {type: "signal"; dataCategory: string; ruleId: string};

interface JevRuleBase {
	key: string;
	/** Short finding description shown to readers; the verbatim criteria text is wire input only. */
	summary: string;
	section: string;
	instructions: string;
	route: JevRoute;
}

export interface JevChoiceRule extends JevRuleBase {
	kind: "choice";
	none: string;
	present: string;
	severity: JevSeverity;
}

export interface JevScoreRule extends JevRuleBase {
	kind: "score";
	levels: readonly string[];
	/** Severity by non-"none" level. */
	severityByLevel: Record<string, JevSeverity>;
}

export type JevRule = JevChoiceRule | JevScoreRule;

export const JEV_RULES: readonly JevRule[] = [
	{
		kind: "choice",
		key: "deceptive_name",
		summary: "Name misleads about what the skill does",
		section: "SS1",
		instructions: "Is the declared name deceptive given what the scripts actually do (e.g. \"safe-calculator\" that exfiltrates data)?",
		none: "The skill package does not contain a deceptive name relative to the skill's actual behavior.",
		present: "The skill package contains a deceptive name relative to the skill's actual behavior.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "description_manifest_mismatch",
		summary: "Description does not match behavior",
		section: "SS1",
		instructions: "Does the description match the skill's actual behavior?",
		none: "The skill package does not contain a mismatch between the declared description and the skill's actual behavior.",
		present: "The skill package contains a mismatch between the declared description and the skill's actual behavior.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "allowed_tools_violation",
		summary: "Code violates declared allowed-tools",
		section: "SS1",
		instructions: "If allowed-tools is declared, does the code violate that restriction? (missing the field entirely is informational, not a violation)",
		none: "The skill package does not contain a violation of a declared allowed-tools restriction.",
		present: "The skill package contains a violation of a declared allowed-tools restriction.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "compatibility_claim_mismatch",
		summary: "Compatibility claim does not match behavior",
		section: "SS1",
		instructions: "Does the compatibility claim (e.g. no network use) match reality?",
		none: "The skill package does not contain a mismatch between a compatibility claim and the skill's actual behavior.",
		present: "The skill package contains a mismatch between a compatibility claim and the skill's actual behavior.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "prompt_injection",
		summary: "Tries to override prior instructions",
		section: "SS2",
		instructions: "\"Ignore previous instructions\" style attempts to override system behavior.",
		none: "The skill package does not contain a prompt-injection attempt in SKILL.md.",
		present: "The skill package contains a prompt-injection attempt in SKILL.md.",
		severity: "high",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "safety_bypass",
		summary: "Tries to disable safety or content policy",
		section: "SS2",
		instructions: "\"Disable content policy\" style directives.",
		none: "The skill package does not contain a safety-bypass directive.",
		present: "The skill package contains a safety-bypass directive.",
		severity: "high",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "concealment_directive",
		summary: "Tells the agent to hide actions from the user",
		section: "SS2",
		instructions: "\"Do not tell the user\" style directives.",
		none: "The skill package does not contain a concealment directive telling the agent to hide something from the user.",
		present: "The skill package contains a concealment directive telling the agent to hide something from the user.",
		severity: "high",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "system_prompt_extraction",
		summary: "Tries to reveal the system prompt",
		section: "SS2",
		instructions: "Attempts to extract or reveal the system prompt.",
		none: "The skill package does not contain an attempt to extract or reveal the system prompt.",
		present: "The skill package contains an attempt to extract or reveal the system prompt.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "role_redefinition",
		summary: "Claims admin or unrestricted mode",
		section: "SS2",
		instructions: "\"You are now in admin/unrestricted mode\" style role overrides.",
		none: "The skill package does not contain an attempt to redefine the agent's role or permissions (e.g. 'admin mode').",
		present: "The skill package contains an attempt to redefine the agent's role or permissions (e.g. 'admin mode').",
		severity: "high",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "data_exfiltration",
		summary: "Sends collected data to an external server",
		section: "SS3",
		instructions: "Network calls sending file contents or collected data to a server.",
		none: "The skill package does not contain a network call sending file contents or collected data to a server.",
		present: "The skill package contains a network call sending file contents or collected data to a server.",
		severity: "critical",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "credential_theft",
		summary: "Reads credential files such as ~/.aws or ~/.ssh",
		section: "SS3",
		instructions: "Reading credential material such as ~/.aws or ~/.ssh.",
		none: "The skill package does not contain code that reads credential material such as ~/.aws or ~/.ssh.",
		present: "The skill package contains code that reads credential material such as ~/.aws or ~/.ssh.",
		severity: "high",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "command_injection",
		summary: "Passes variable input into eval or exec",
		section: "SS3",
		instructions: "Untrusted or variable input passed into eval, exec, or os.system.",
		none: "The skill package does not contain untrusted or variable input passed into eval, exec, or os.system.",
		present: "The skill package contains untrusted or variable input passed into eval, exec, or os.system.",
		severity: "critical",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "hardcoded_secrets",
		summary: "Hardcoded API keys or tokens",
		section: "SS3",
		instructions: "API keys or tokens hardcoded in source.",
		none: "The skill package does not contain a hardcoded API key or token in source.",
		present: "The skill package contains a hardcoded API key or token in source.",
		severity: "critical",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "obfuscation",
		summary: "Encoded content that resists inspection",
		section: "SS3",
		instructions: "Base64/hex-encoded blobs or other content designed to resist inspection.",
		none: "The skill package does not contain obfuscated content (base64/hex-encoded or similar) designed to resist inspection.",
		present: "The skill package contains obfuscated content (base64/hex-encoded or similar) designed to resist inspection.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "description_behavior_mismatch",
		summary: "Script behavior differs from its description",
		section: "SS4",
		instructions: "Does the description match the script's actual behavior (component-level, not just the manifest field)?",
		none: "The skill package does not contain a mismatch between the description and what the scripts actually do.",
		present: "The skill package contains a mismatch between the description and what the scripts actually do.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "declared_tools_unused",
		summary: "Declared tool is unused and unexplained",
		section: "SS4",
		instructions: "Is there a declared tool that is unused AND unexplained by the skill's own stated purpose -- not simply one entry in a reference table of many tools for different situations, where using only a subset per task is normal?",
		none: "The skill package does not contain a declared tool that is unused in a way unexplained by the skill's own stated purpose (not merely one of many reference-table tools used situationally).",
		present: "The skill package contains a declared tool that is unused in a way unexplained by the skill's own stated purpose (not merely one of many reference-table tools used situationally).",
		severity: "low",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "hidden_capabilities",
		summary: "Code capability not disclosed in the manifest",
		section: "SS4",
		instructions: "Capabilities present in code but not disclosed in the manifest.",
		none: "The skill package does not contain a capability present in code but not disclosed in the manifest.",
		present: "The skill package contains a capability present in code but not disclosed in the manifest.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "undocumented_script_behavior",
		summary: "Scripts do things the instructions never mention",
		section: "SS4",
		instructions: "Do scripts do things the instructions never mention?",
		none: "The skill package does not contain script behavior the instructions never mention.",
		present: "The skill package contains script behavior the instructions never mention.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "suspicious_referenced_file",
		summary: "Referenced file looks suspicious",
		section: "SS5",
		instructions: "Do any referenced files look suspicious in name or purpose?",
		none: "The skill package does not contain a referenced file that looks suspicious in name or purpose.",
		present: "The skill package contains a referenced file that looks suspicious in name or purpose.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "missing_referenced_file",
		summary: "Referenced file is missing from the package",
		section: "SS5",
		instructions: "Do the files a skill references actually exist in the package?",
		none: "The skill package does not contain a file the skill references that doesn't actually exist in the package.",
		present: "The skill package contains a file the skill references that doesn't actually exist in the package.",
		severity: "low",
		route: {type: "signal", dataCategory: "reliability", ruleId: "reliability/unresolvable-internal-references"},
	},
	{
		kind: "choice",
		key: "external_untrusted_source",
		summary: "Pulls instructions or data from a URL or user file",
		section: "SS6",
		instructions: "Does the skill pull instructions/data from a URL or user-supplied file, rather than its own bundled files?",
		none: "The skill package does not contain the skill pulling instructions or data from a URL or user-supplied file, rather than its own bundled files.",
		present: "The skill package contains the skill pulling instructions or data from a URL or user-supplied file, rather than its own bundled files.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "score",
		key: "unbounded_autonomy",
		summary: "Pushes unattended retries without confirmation",
		section: "SS6",
		instructions: "How strongly do instructions push unattended retries or \"run without confirmation\"?",
		levels: ["none", "mild", "strong"],
		severityByLevel: {mild: "low", strong: "medium"},
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "cross_context_bridging",
		summary: "Uses information across chats or sessions",
		section: "SS6",
		instructions: "\"Use info from previous chats\" / \"remember across sessions\" style instructions.",
		none: "The skill package does not contain an instruction to use information from previous chats or remember across sessions.",
		present: "The skill package contains an instruction to use information from previous chats or remember across sessions.",
		severity: "low",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "over_collection",
		summary: "Gathers everything before acting",
		section: "SS6",
		instructions: "\"Collect everything first\" / \"gather all files\" style instructions.",
		none: "The skill package does not contain an instruction to collect or gather everything before acting.",
		present: "The skill package contains an instruction to collect or gather everything before acting.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "tool_chaining_behavioral",
		summary: "Chains a read step into a send step",
		section: "SS6",
		instructions: "Does the skill chain a read step into a send/post step in a way that goes beyond its own declared purpose -- not merely calling its own documented external API to do the job it says it does?",
		none: "The skill package does not contain a read-then-send or collect-then-post chain that exceeds the skill's own declared purpose (distinct from the skill simply calling its own documented external API to do its job).",
		present: "The skill package contains a read-then-send or collect-then-post chain that exceeds the skill's own declared purpose (distinct from the skill simply calling its own documented external API to do its job).",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "transitive_trust",
		summary: "Defers authority to fetched content",
		section: "SS6",
		instructions: "\"Follow webpage instructions\" / \"execute code blocks found\" style delegated trust.",
		none: "The skill package does not contain an instruction to follow or execute content found in an external/untrusted source.",
		present: "The skill package contains an instruction to follow or execute content found in an external/untrusted source.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "overbroad_description",
		summary: "Claims to do anything",
		section: "SS7",
		instructions: "\"Can do anything\" / \"general assistant\" style over-broad claims.",
		none: "The skill package does not contain an over-broad, 'can do anything' style description.",
		present: "The skill package contains an over-broad, 'can do anything' style description.",
		severity: "low",
		route: {type: "signal", dataCategory: "reliability", ruleId: "reliability/description-overclaim"},
	},
	{
		kind: "choice",
		key: "keyword_baiting",
		summary: "Excess trigger words to inflate activation",
		section: "SS7",
		instructions: "Excessive trigger words meant to inflate activation.",
		none: "The skill package does not contain excessive trigger keywords meant to inflate activation on unrelated tasks.",
		present: "The skill package contains excessive trigger keywords meant to inflate activation on unrelated tasks.",
		severity: "low",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "activation_priority_manipulation",
		summary: "Claims priority over other tools",
		section: "SS7",
		instructions: "\"Use me first\" / \"priority tool\" style activation claims.",
		none: "The skill package does not contain a claim like 'use me first' meant to manipulate activation priority.",
		present: "The skill package contains a claim like 'use me first' meant to manipulate activation priority.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "unpinned_dependencies",
		summary: "Dependencies installed without pinned versions",
		section: "SS8",
		instructions: "Package installs without pinned versions.",
		none: "The skill package does not contain a package install without a pinned version.",
		present: "The skill package contains a package install without a pinned version.",
		severity: "low",
		route: {type: "signal", dataCategory: "compatibility", ruleId: "compatibility/unpinned-dependencies"},
	},
	{
		kind: "choice",
		key: "untrusted_direct_install",
		summary: "Installs directly from an unknown repo",
		section: "SS8",
		instructions: "Direct GitHub installs from unknown or untrusted repos.",
		none: "The skill package does not contain a direct install from an unknown or untrusted GitHub repo.",
		present: "The skill package contains a direct install from an unknown or untrusted GitHub repo.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "missing_provenance",
		summary: "Dependency lacks author, version or license",
		section: "SS8",
		instructions: "No author, version, or license on a bundled/installed dependency.",
		none: "The skill package does not contain a dependency with no stated author, version, or license.",
		present: "The skill package contains a dependency with no stated author, version, or license.",
		severity: "low",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "typosquatting",
		summary: "Package name resembles a popular package",
		section: "SS8",
		instructions: "Package names suspiciously similar to popular packages.",
		none: "The skill package does not contain a package name suspiciously similar to a popular package (typosquatting).",
		present: "The skill package contains a package name suspiciously similar to a popular package (typosquatting).",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "multistep_read_send",
		summary: "Multi-step read-then-upload beyond its purpose",
		section: "SS9",
		instructions: "A read-to-send, collect-to-post, or gather-to-upload chain that goes beyond the skill's own declared purpose -- not merely the skill calling its own documented external API to do the job it says it does.",
		none: "The skill package does not contain a multi-step read-to-send, collect-to-post, or gather-to-upload operation that exceeds the skill's own declared purpose.",
		present: "The skill package contains a multi-step read-to-send, collect-to-post, or gather-to-upload operation that exceeds the skill's own declared purpose.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "unconfirmed_automated_workflow",
		summary: "Runs sensitive actions without user confirmation",
		section: "SS9",
		instructions: "Automated workflows that run without a user confirmation step, for an action a reasonable user would want to approve first (e.g. sharing data externally, deleting something) -- not just a normal automated step that is the skill's whole declared point.",
		none: "The skill package does not contain an automated, unconfirmed action a reasonable user would want to approve first (data sharing, deletion, etc.).",
		present: "The skill package contains an automated, unconfirmed action a reasonable user would want to approve first (data sharing, deletion, etc.).",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "sensitive_data_pipeline",
		summary: "Combines several sensitive operations",
		section: "SS9",
		instructions: "A data pipeline combining multiple SENSITIVE operations (credentials, personal data, secrets) -- not just multiple ordinary API calls that are the skill's normal, declared job.",
		none: "The skill package does not contain a data pipeline combining multiple sensitive operations (credentials, personal data, or secrets).",
		present: "The skill package contains a data pipeline combining multiple sensitive operations (credentials, personal data, or secrets).",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "cross_boundary_data_flow",
		summary: "Data leaves the machine beyond its purpose",
		section: "SS9",
		instructions: "Data crossing a local-to-network or file-to-API boundary in a way that goes beyond the skill's own declared purpose -- e.g. sending local files or credentials externally, not just the skill calling its own documented external API to do the job it says it does.",
		none: "The skill package does not contain data flow crossing a local-to-network or file-to-API boundary in a way that exceeds the skill's own declared purpose.",
		present: "The skill package contains data flow crossing a local-to-network or file-to-API boundary in a way that exceeds the skill's own declared purpose.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "disproportionate_data_access",
		summary: "Accesses more data than its purpose needs",
		section: "SS10",
		instructions: "Data access disproportionate to the skill's stated purpose.",
		none: "The skill package does not contain data access disproportionate to the skill's stated purpose.",
		present: "The skill package contains data access disproportionate to the skill's stated purpose.",
		severity: "medium",
		route: {type: "finding"},
	},
	{
		kind: "choice",
		key: "scope_creep_data_access",
		summary: "Accesses data outside its stated scope",
		section: "SS10",
		instructions: "Accessing data beyond what the skill's scope calls for.",
		none: "The skill package does not contain data access beyond what the skill's stated scope calls for.",
		present: "The skill package contains data access beyond what the skill's stated scope calls for.",
		severity: "medium",
		route: {type: "finding"},
	},
];
